dist: bionic
language: node_js
node_js:
- 12

addons:
  apt:
    packages:
      - pulseaudio

env:
  global:
    - DISPLAY=:99.0

  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly
    - BROWSER=firefox BVER=esr

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_script:
  - export CHROME_BIN=browsers/bin/chrome-${BVER}
  - export FIREFOX_BIN=browsers/bin/firefox-${BVER}
  - Xvfb :99 &
  - pulseaudio --start
  - node_modules/travis-multirunner/setup.sh

script:
  - npm test
